<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */

/**
 * @var \Magento\Backend\Block\Store\Switcher $block
 * @var \Magefan\Community\Api\SecureHtmlRendererInterface $mfSecureRenderer
 */
?>
<?php if ($websites = $block->getWebsites()): ?>
    <div class="store-switcher store-view">
        <span class="store-switcher-label"><?= $block->escapeHtml(__('Scope:')) ?></span>
        <div class="actions dropdown closable">
            <input type="hidden" name="store_switcher" id="store_switcher"
                   data-role="store-view-id" data-param="<?= $block->escapeHtmlAttr($block->getStoreVarName()) ?>"
                   value="<?= $block->escapeHtml($block->getStoreId()) ?>"
                <?= /* @noEscape */ $block->getUiId() ?> />
            <input type="hidden" name="store_group_switcher" id="store_group_switcher"
                   data-role="store-group-id" data-param="<?= $block->escapeHtmlAttr($block->getStoreGroupVarName()) ?>"
                   value="<?= $block->escapeHtml($block->getStoreGroupId()) ?>"
                <?= /* @noEscape */ $block->getUiId() ?> />
            <input type="hidden" name="website_switcher" id="website_switcher"
                   data-role="website-id" data-param="<?= $block->escapeHtmlAttr($block->getWebsiteVarName()) ?>"
                   value="<?= $block->escapeHtml($block->getWebsiteId()) ?>"
                <?= /* @noEscape */ $block->getUiId() ?> />
            <button
                type="button"
                class="admin__action-dropdown"
                data-mage-init='{"dropdown":{}}'
                data-toggle="dropdown"
                aria-haspopup="true"
                id="store-change-button">
                <?= $block->escapeHtml($block->getCurrentSelectionName()) ?>
            </button>
            <ul class="dropdown-menu" data-role="stores-list">
                <?php if ($block->hasDefaultOption()): ?>
                    <li class="store-switcher-all disabled current">
                        <span><?= $block->escapeHtml($block->getDefaultSelectionName()) ?></span>
                    </li>
                <?php endif; ?>
                <?php foreach ($websites as $website): ?>
                    <?php $showWebsite = false; ?>
                    <?php foreach ($website->getGroups() as $group): ?>
                        <?php $showGroup = false; ?>
                        <?php foreach ($block->getStores($group) as $store): ?>
                            <?php if ($showWebsite == false): ?>
                                <?php $showWebsite = true; ?>
                                <li class="store-switcher-website">
                                    <a data-role="mf-promo-switcher" href="#">
                                        <?= $block->escapeHtml($website->getName()) ?>
                                    </a>
                                </li>
                            <?php endif; ?>
                            <?php if ($showGroup == false): ?>
                                <?php $showGroup = true; ?>
                                <li class="store-switcher-store">
                                    <a data-role="mf-promo-switcher" href="#">
                                        <?= $block->escapeHtml($group->getName()) ?>
                                    </a>
                                </li>
                            <?php endif; ?>
                            <li class="store-switcher-store-view">
                                <a data-role="mf-promo-switcher" href="#">
                                    <?= $block->escapeHtml($store->getName()) ?>
                                </a>
                            </li>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </ul>
        </div>
        <?= $block->getHintHtml() ?>
    </div>

    <?php $script = "
        require(['jquery', 'Magefan_Translation/js/mf-upgrade-plan-popup', 'domReady!'], function ($, mfPopup) {
            $(\"[data-role='mf-promo-switcher']\").on('click', function (e) {
                e.preventDefault();
                e.stopPropagation();
                mfPopup('Plus or Extra', 'auto-translate', 'store-switcher');
                return false;
            });
        });
    "; ?>

    <?= /* @noEscape */ $mfSecureRenderer->renderTag('script', [], $script, false) ?>

<?php endif; ?>
