<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * @var $block \Magefan\Translation\Block\Adminhtml\System\Config\Form\CurrentUsage
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<div class="mf-tr-api-usage" style="background: #ccc; padding: 5px;">
    <?= $escaper->escapeHtml(__('Today’s Usage: %1', $block->getUsed())) ?>
</div>
